version: 2

# define first all the single commands ... for reuse

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v2-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "requirements.txt" }}
      - v2-dependencies-{{ .Environment.CIRCLE_BRANCH }}-

save_cache: &save_cache
  save_cache:
    paths:
      - ./venv
    key: v2-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "requirements.txt" }}

install_dependencies: &install_dependencies
  run:
    name: install dependencies
    command: |
      python3 -m venv venv
      . venv/bin/activate
      make pip3
      pip list

run_coverage: &run_coverage
  run:
    name: run coverage
    command: |
      . venv/bin/activate
      make coverage

report_codecov: &report_codecov
  run:
    name: report codecov
    command: |
      . venv/bin/activate
      make codecov

show_python_version: &show_python_version
  run:
    name: python version
    command: |
      python --version

terraform_plan: &terraform_plan
  run:
    name: terraform plan
    command: |
      cd terraform
      terraform init
      terraform plan


# defining the steps for each job

coverage_steps: &coverage_steps
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *install_dependencies
    - <<: *show_python_version
    - <<: *run_coverage
    - <<: *save_cache
    - <<: *report_codecov

plan_steps: &plan_steps
  steps:
    - checkout
    - <<: *terraform_plan

# job definitions

jobs:
  coverage:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    <<: *coverage_steps

  plan:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo
    <<: *plan_steps

# dependencies for the workflow

workflows:
  version: 2
  test:
    jobs:
      - coverage:
          context: trello
      - plan:
          context: trello_deploy
